#!/usr/bin/env bash

is_command_not_in_path() { ! [ -x "$(command -v "$1")" ]; }

if is_command_not_in_path brew; then
	echo 'Installing brew...'
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew update

brew bundle install --file brew/Brewfile

brew doctor
