#!/usr/bin/env bash

source utility/command.sh

if is_command_not_in_path brew; then
	printf 'Installing brew...\n'
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew update

brew bundle install --file brew/Brewfile

brew doctor
