#!/usr/bin/env bash

SESSION='BrunoRoque06'

tmux new-session -s $SESSION -n 'dotfiles' -d
tmux send-keys "cd $HOME/Projects/dotfiles" C-m

tmux new-window -t $SESSION:1 -n 'website'
tmux split-window -h -t $SESSION:1.0
tmux send-keys -t $SESSION:1.0 "cd $HOME/Projects/brunoroque06.github.io" C-m
tmux send-keys -t $SESSION:1.1 "cd $HOME/Projects/brunoroque06.github.io; make serve" C-m

tmux new-window -t $SESSION:2 -n 'lambda'
tmux send-keys "cd $HOME/Projects/lambda" C-m

tmux attach-session -t $SESSION
