#!/usr/bin/env bash

SESSION='brunoroque06'

tmux new-session -s $SESSION -n 'dotfiles' -d
tmux send-keys "cd $HOME/Projects/dotfiles" C-m

tmux new-window -t $SESSION -n 'website'
tmux split-window -h -t $SESSION:2
tmux send-keys -t $SESSION:2.0 "cd $HOME/Projects/brunoroque06.github.io" C-m
tmux send-keys -t $SESSION:2.1 "cd $HOME/Projects/brunoroque06.github.io; make serve" C-m

tmux new-window -t $SESSION -n 'lambda'
tmux send-keys "cd $HOME/Projects/lambda" C-m

tmux attach-session -t $SESSION
