#!/usr/bin/env bash

SESSION='RaccoonWorks'

tmux new-session -s $SESSION -n 'dotfiles' -d
tmux send-keys "cd $HOME/Projects/dotfiles" C-m

tmux new-window -t $SESSION:1 -n 'Project'
tmux send-keys "cd $HOME/Projects/raccoon-works/FFE" C-m

tmux attach-session -t $SESSION
