#!/usr/bin/env bash

SESSION='Spoud'

tmux new-session -s $SESSION -n 'dotfiles' -d
tmux send-keys "cd $HOME/Projects/dotfiles" C-m

tmux new-window -t $SESSION:1 -n 'Monorepository'
tmux send-keys 'mrcd; gl' C-m

tmux new-window -t $SESSION:2 -n 'Catalog'
tmux split-window -v -t $SESSION:2.0
tmux split-window -v -t $SESSION:2.0
tmux select-layout even-vertical

tmux send-keys -t $SESSION:2.0 'mrcd; sleep 10; bazel run catalog/service:app' C-m
tmux send-keys -t $SESSION:2.1 'mrcd; sleep 5; bazel run catalog/worker/metrics/service:app' C-m
tmux send-keys -t $SESSION:2.2 "docker-compose -f $HOME/Projects/dotfiles/tmux/scripts/spoud-catalog.yml up --abort-on-container-exit" C-m

tmux attach-session -t $SESSION
