#!/usr/bin/env bash

SESSION='Spoud'

tmux new-session -s $SESSION -n 'dotfiles' -d
tmux send-keys "cd $HOME/Projects/dotfiles" C-m

tmux new-window -t $SESSION:1 -n 'MonoRepo'
tmux send-keys 'mrcd; gl' C-m

tmux new-window -t $SESSION:2 -n 'Catalog'
tmux split-window -v -t $SESSION:2.0
tmux split-window -v -t $SESSION:2.0
tmux select-layout even-vertical
tmux split-window -h -t $SESSION:2.2

tmux send-keys -t $SESSION:2.1 'mrcd; sleep 10; populator_active=true spring_jpa_properties_hibernate_generate_ddl=true spring_jpa_properties_hibernate_hbm2ddl_auto=create-drop bazel run catalog/service:app' C-m
tmux send-keys -t $SESSION:2.2 'mrcd; cd catalog/client; npm run serve' C-m
tmux send-keys -t $SESSION:2.3 "docker-compose -f $HOME/Projects/dotfiles/tmux/scripts/spoud-catalog.yml up postgres" C-m

tmux attach-session -t $SESSION
