#!/usr/bin/env bash

source utilities/command.sh

if does_command_not_exist brew; then
  printf 'Installing brew...'
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update

brew install bat
brew install diff-so-fancy
brew install exa
brew install fish
brew install ghc cabal-install
brew install git jesseduffield/lazygit/lazygit
brew install go
brew install htop
brew install java gradle
brew install jq
brew install kafka
brew install node
brew install pyenv
brew install python
brew install shellcheck shfmt
brew install tmux
brew install vim
brew install wget
brew install zsh

brew cask install alacritty
brew cask install google-chrome
brew cask install visual-studio-code

brew doctor
