#!/usr/bin/env bash

source utilities/shell

sudo pacman -S --needed alacritty bat diff-so-fancy exa fish git go-pie gradle htop jq nodejs npm shellcheck shfmt python python-pip tmux gvim wget xclip zsh

if does_command_not_exist yay; then
  git clone --depth 1 https://aur.archlinux.org/yay.git
  (
    cd yay/ || exit
    makepkg -si
  )
  rm -rf yay/
fi

yay -S --needed google-chrome lazygit otf-sfmono visual-studio-code-bin
