#!/usr/bin/env bash

source utilities/os
source utilities/shell

if is_mac_os; then
  printf 'Installing brew packages/casks...\n'
  prompt_for_command ./package-managers/brew
elif is_arch; then
  printf 'Installing pacman packages...\n'
  prompt_for_command ./package-managers/pacman
fi
