#!/usr/bin/env bash

source utilities/command.sh
source utilities/logging.sh
source utilities/os.sh

if is_mac_os; then
	logging_setup 'brew'
	prompt_for_command ./package-managers/brew
elif is_arch; then
	logging_setup 'pacman'
	prompt_for_command ./package-managers/pacman
fi
