#!/usr/bin/env bash

source utils

if does_command_not_exist brew; then
  printf 'Installing brew...'
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update

brew install bat
brew install cmake
brew install diff-so-fancy
brew install fzf
printf 'y\ny\nn\n' | "$(brew --prefix)"/opt/fzf/install
brew install getantibody/tap/antibody
brew install git
brew install go
brew install htop
brew install jesseduffield/lazygit/lazygit
brew install node
brew install python
brew install shellcheck
brew install shfmt
brew install tmux
brew install vim
brew install wget
brew install zsh

brew cask install google-chrome
brew cask install visual-studio-code

brew upgrade
brew cleanup
brew doctor
