#!/usr/bin/env bash

brew update

brew install antibody
brew install diff-so-fancy
brew install git
brew install node
brew install shellcheck
brew install vim
brew install zsh

brew cleanup

brew doctor
