#!/usr/bin/env bash

brew update

brew install antibody
brew install bat
brew install cmake
brew install diff-so-fancy
brew install git
brew install go
brew tap jesseduffield/lazygit
brew install lazygit
brew install node
brew install reattach-to-user-namespace
brew install shellcheck
brew install tmux
brew install vim
brew install zsh

brew cleanup

brew doctor

