#!/usr/bin/env bash

set -e

install() {
	./brew/setup

	SH=/opt/homebrew/bin/bash
	grep -qxF $SH /etc/shells || printf "$SH\n" | sudo tee -a /etc/shells
	chsh -s $SH
}

link() {
	mkdir -p "$2"
	stow -"$1" -v 1 -t "$2" "$3"
}

link_manager() {
	link "$1" "$HOME/.elvish" elvish
	link "$1" "$HOME/.config/fish" fish
	link "$1" "$HOME" git
	link "$1" "$HOME" gnu-readline
	link "$1" "$HOME" jetbrains
	link "$1" "$HOME/.config/nvim" neovim
	link "$1" "$HOME" postgresql
	link "$1" "$HOME/.config" ripgrep
	link "$1" "$HOME/Library/Application Support/Code/User" vscode
}

case "$1" in
install)
	install
	;;
link)
	link_manager S
	;;
unlink)
	link_manager D
	;;
*)
	printf 'Available Commands:\n\ninstall\nlink\nunlink\n'
	;;
esac
