#!/usr/bin/env bash

set -e

install() {
	./brew/setup

	SH=/opt/homebrew/bin/bash
	grep -qxF $SH /etc/shells || echo $SH | sudo tee -a /etc/shells
	chsh -s $SH
	echo "export PATH=/opt/homebrew/bin:$PATH" >~/.bash_profile

	wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/NerdFontsSymbolsOnly/complete/Symbols-1000-em%20Nerd%20Font%20Complete%20Mono.ttf -O "$HOME/Library/Fonts/Symbols-1000-em Nerd Font Complete Mono.ttf"

	defaults write -g ApplePressAndHoldEnabled -bool true
}

paths=(
	elvish "$HOME/.config/elvish"
	git "$HOME"
	jetbrains "$HOME"
	neovim "$HOME/.config/nvim"
	nushell "$HOME/Library/Application Support/nushell"
	postgresql "$HOME"
	ripgrep "$HOME/.config"
	vscode "$HOME/Library/Application Support/Code/User"
)

link() {
	mkdir -p "$2"
	stow -S -v 1 -t "$2" "$1"
}

unlink() {
	stow -D -v 1 -t "$2" "$1"
}

link_manager() {
	for ((i = 0; i < ${#paths[@]}; i += 2)); do
		$1 "${paths[i]}" "${paths[i + 1]}"
	done
}

case "$1" in
install)
	install
	;;
link)
	link_manager link
	;;
unlink)
	link_manager unlink
	;;
*)
	printf 'Available Commands:\n'
	for o in $(grep -e '[a-z])' dotfiles | tr -d ')'); do printf '  %s\n' "$o"; done
	;;
esac
