#!/usr/bin/env bash

set -e

setup() {
	if [ ! -f /opt/homebrew/bin/brew ]; then
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi

	brew update
	brew bundle install --file brew/brewfile --no-lock
	brew doctor

	SH=/opt/homebrew/bin/bash
	if ! grep -q $SH /etc/shells; then
		printf '%s\n' $SH | sudo tee -a /etc/shells
		chsh -s $SH
	fi

	if ! grep -q homebrew "$HOME"/.bash_profile; then
		printf 'export PATH=/opt/homebrew/bin:%s\n' "$PATH" >"$HOME/.bash_profile"
	fi
}

paths=(
	elvish "$HOME"/.config/elvish
	git "$HOME"/.config/git
	jetbrains "$HOME"
	kitty "$HOME"/.config/kitty
	postgresql "$HOME"
	powershell "$HOME"/.config/powershell
	ripgrep "$HOME"/.config
	vim "$HOME"
	vscode "$HOME/Library/Application Support/Code/User"
)

link() {
	mkdir -p "$2"
	stow -S -v 1 -t "$2" "$1"
}

unlink() {
	stow -D -v 1 -t "$2" "$1"
}

for_config() {
	for ((i = 0; i < ${#paths[@]}; i += 2)); do
		$1 "${paths[i]}" "${paths[i + 1]}"
	done
}

case "$1" in
setup)
	setup
	;;
config)
	for_config link
	dotnet fsi keybinds.fsx
	;;
unconfig)
	for_config unlink
	;;
*)
	printf 'Commands:\n'
	for o in $(grep -e '[a-z])$' dots | tr -d ')'); do printf '  %s\n' "$o"; done
	;;
esac
