#!/usr/bin/env bash

source utilities/os.sh

printf 'Starting dotfiles installation...\n'

./package-managers/setup

./font/setup

./python/setup
./fish/setup
./vim/setup
./git/setup
./tmux/setup
./fzf/setup

if is_arch; then
	./i3/setup
fi

./alacritty/setup
./vscode/setup
./intellij/setup

printf 'Installation has finished #\n'

exec fish
