#!/usr/bin/env bash

source utils

printf 'Starting dotfiles installation...\n'

./git/setup
./intellij/setup
./tmux/setup
./vim/setup
./zsh/setup

if is_mac_os; then
  ./terminal/setup
  printf 'Installing brew packages/casks...\n'
  ./brew
elif is_arch; then
  printf 'Installing pacman packages...\n'
  ./pacman
fi

./vscode/setup

printf 'Installation has finished.\n'

exec zsh
