#!/usr/bin/env bash

printf 'Starting dotfiles installation...\n'

./package-manager/setup

./alacritty/setup
./fish/setup
./fzf/setup
./git/setup
./jetbrains/setup
./lazygit/setup
./lf/setup
./node/setup
./python/setup
./postgresql/setup
./starship/setup
./tmux/setup
./vim/setup
./vscode/setup
./window-manager/setup

printf 'Installation has finished #\n'

exec fish
