#!/usr/bin/env bash

sudo pacman -S bat cmake diff-so-fancy git go-pie htop nodejs npm shellcheck python tmux vim wget zsh

if ! [ -x "$(command -v yay)" ]; then
  git clone https://aur.archlinux.org/yay.git
  (cd yay/ || exit ; makepkg -si)
  rm -rf yay/
fi

yay -S antibody google-chrome lazygit otf-san-francisco pamac visual-studio-code-bin

