#!/usr/bin/env bash

printf 'Pre-commit hook started\n\n'

fd --hidden --type x . | xargs -t -I {} shellcheck -x {}
fd --hidden --type x . | xargs -t -I {} shfmt -w {}

fd --hidden --type f '.*\.sh$' . | xargs -t -I {} shellcheck -x {}
fd --hidden --type f '.*\.sh$' . | xargs -t -I {} shfmt -w {}

prettier --write '**/*.{json,md,yaml,yml}'

printf '\nPre-commit hook finished\n'
