#!/usr/bin/env bash

does_command_not_exist() { ! [ -x "$(command -v $1)" ]; }

is_mac_os() { [ "$(uname)" == "Darwin" ]; }

is_arch() { [ "$(uname)" == "Linux" ]; }

symlink_to_home() {
  FILE=$(basename $1)
  ln -fns $1 $HOME/$FILE
}
