#!/usr/bin/env bash

source utilities/os

printf 'Installing font...\n'

readonly FONT_ZIP='font.zip'
curl --compressed --output $FONT_ZIP 'http://input.fontbureau.com/build/?fontSelection=fourStyleFamily&regular=InputMonoNarrow-Regular&italic=InputMonoNarrow-Italic&bold=InputMonoNarrow-Bold&boldItalic=InputMonoNarrow-BoldItalic&a=0&g=ss&i=serif&l=serif&zero=slash&asterisk=height&braces=0&preset=default&line-height=1.2&accept=I+do&email='

readonly TEMP_DIR='temp'
unzip -j $FONT_ZIP '*.ttf' -d $TEMP_DIR

if is_mac_os; then
  cp "$TEMP_DIR"/*.ttf "$HOME"/Library/Fonts
elif is_arch; then
  readonly FONTS_DIR="$HOME"/.local/share/fonts
  mkdir -p "$FONTS_DIR"
  cp "$TEMP_DIR"/*.ttf "$FONTS_DIR"
fi

rm -rf $FONT_ZIP $TEMP_DIR

