#!/usr/bin/env bash

source utility/logging.sh
source utility/os.sh

install_font() {
	readonly FONT_ZIP='font.zip'
	curl --compressed --output $FONT_ZIP 'http://input.fontbureau.com/build/?fontSelection=fourStyleFamily&regular=InputMono-Regular&italic=InputMono-Italic&bold=InputMono-Bold&boldItalic=InputMono-BoldItalic&a=0&g=ss&i=serif&l=serif&zero=0&asterisk=height&braces=0&preset=default&line-height=1.2&accept=I+do&email='
	readonly TEMP_DIR='temp'
	unzip -j $FONT_ZIP '*.ttf' -d $TEMP_DIR
	mkdir -p "$1"
	cp "$TEMP_DIR"/*.ttf "$1"
	rm -rf $FONT_ZIP $TEMP_DIR
}

install_font_if_not_yet_installed() {
	if ls "$1"/Input*.ttf 1>/dev/null 2>&1; then
		printf 'Font is already installed'
	else
		install_font "$1"
	fi
}

logging_setup 'font'

if is_mac_os; then
	install_font_if_not_yet_installed "$HOME"/Library/Fonts
elif is_arch; then
	install_font_if_not_yet_installed "$HOME"/.local/share/fonts
fi
