theme = "github_light_high_contrast"

[editor]
color-modes = true
# end-of-line-diagnostics = "hint"
line-number = "relative"
shell = ["/opt/homebrew/bin/nu", "-c"]
trim-trailing-whitespace = true

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 1000

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.insert]
C-a = "goto_line_start"
C-b = "move_char_left"
C-e = "goto_line_end_newline"
C-f = "move_char_right"
C-x = "completion"

[keys.normal]
space."=" = ":format"

[keys.normal."\\".g]
b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
d = ":! git diff %{buffer_name}"
r = ":reset-diff-change"
R = [":echo %sh{git restore %{buffer_name}}", ":reload"]
