theme = "github_light_high_contrast"

[editor]
color-modes = true
line-number = "relative"
trim-trailing-whitespace = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.insert]
C-a = "goto_line_start"
C-b = "move_char_left"
C-e = "goto_line_end_newline"
C-f = "move_char_right"
C-x = "completion"

[keys.normal]
space."=" = ":format"
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
