set nocompatible

" Buffers
set hidden
nnoremap gb :ls<CR>:b<Space>

" Clipboard
set clipboard^=unnamed,unnamedplus

" Files
set autoread
set path+=**
set noswapfile

" Indentation
set expandtab
set shiftwidth=2
set softtabstop=2

" Mapping
set backspace=indent,eol,start
set ttimeoutlen=0

" Mouse
set ttymouse=xterm2
set mouse=a

" Search
set ignorecase
set incsearch
set hlsearch
set smartcase

" Text
syntax enable
set encoding=utf-8
augroup markdownSpell
  autocmd!
  autocmd FileType markdown setlocal spell
  autocmd BufRead,BufNewFile *.md setlocal spell
augroup END

" UI
set cursorline
set laststatus=2
set lazyredraw
set number
set scrolloff=10
set showcmd
set wildmenu

" Theme
set background=dark
colorscheme gruvbox
highlight SpellBad cterm=underline ctermfg=DarkRed gui=underline guifg=DarkRed
 
" FZF
set rtp+=~/.fzf
map <C-T> :FZF<CR>

