#!/usr/bin/env bash

source utility/logging.sh
source utility/os.sh

logging_setup 'window manager'

if is_mac_os; then
	./window-manager/macos/setup
elif is_arch_linux; then
	./window-manager/arch/setup
fi
