#!/usr/bin/env bash

source utilities/file.sh
source utilities/logging.sh

logging_setup 'i3'

symlink_to_dir i3.conf "$HOME"/.config/i3/config
symlink_to_dir i3status.conf "$HOME"/.config/i3status/config
