#!/usr/bin/env bash

source utilities/logging.sh

logging_setup 'i3'

mkdir -p "$HOME"/.config/i3
ln -fsv "$PWD"/i3/i3.conf "$HOME"/.config/i3/config

mkdir -p "$HOME"/.config/i3status
ln -fsv "$PWD"/i3/i3status.conf "$HOME"/.config/i3status/config
