#!/usr/bin/env bash

source utility/logging.sh

logging_setup 'fzf'

readonly FZF_DIR="$HOME"/.fzf
rm -rf "$FZF_DIR"
mkdir -p "$FZF_DIR"

git clone --depth 1 https://github.com/junegunn/fzf.git "$FZF_DIR"

printf 'y\ny\nn\n' | "$FZF_DIR"/install

rm "$HOME"/.fzf.bash
