#!/usr/bin/env bash

printf 'Setting up fzf...\n'

readonly FZF_DIR="$HOME"/.fzf
mkdir -p "$FZF_DIR"

git -C "$FZF_DIR" pull --depth 1 || git clone --depth 1 https://github.com/junegunn/fzf.git "$FZF_DIR"

printf 'y\ny\nn\n' | "$FZF_DIR"/install

rm "$HOME"/.fzf.bash

