#!/usr/bin/env bash

source utility/dotfile.sh
source utility/logging.sh

logging_setup 'vscode'

printf 'Symlinking VSCode configuration...\n'
CONFIG="$HOME/Library/Application Support/Code/User"

link settings.json "$CONFIG"
link keybindings.json "$CONFIG"

printf 'Installing VSCode extensions...\n'
link extensions.txt "$HOME"/.vscode
xargs <"$HOME"/.vscode/extensions.txt -L 1 code --force --install-extension
