#!/usr/bin/env bash

source utility/file.sh
source utility/logging.sh
source utility/os.sh

logging_setup 'vscode'

printf 'Symlinking VSCode configuration...\n'
if is_mac_os; then
	CONFIG="$HOME/Library/Application Support/Code/User"
elif is_arch_linux; then
	CONFIG="$HOME/.config/Code - OSS/User"
fi

symlink_to_dir settings.json "$CONFIG"
symlink_to_dir keybindings.json "$CONFIG"

printf 'Installing VSCode extensions...\n'
symlink_to_dir extensions.txt "$HOME"/.vscode
xargs <"$HOME"/.vscode/extensions.txt -L 1 code --force --install-extension
