#!/usr/bin/env bash

source utility/file.sh
source utility/logging.sh

logging_setup 'bspwm'

symlink_to_dir bspwmrc "$HOME"/.config/bspwm
symlink_to_dir sxhkdrc "$HOME"/.config/sxhkd
symlink_to_dir config "$HOME"/.config/polybar
