#!/usr/bin/env bash

source utility/logging.sh

logging_setup 'python'

pip install --upgrade pip

pip install --upgrade black
pip install --upgrade pre-commit
pip install --upgrade pylint
pip install --upgrade ranger-fm
