#!/usr/bin/env bash

source utility/command.sh

if is_command_not_in_path brew; then
	printf 'Installing brew...'
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update

xargs brew install <package-manager/packages.txt
brew install cjbassi/gotop/gotop jesseduffield/lazygit/lazygit starship

brew tap homebrew/cask-fonts
brew cask install alacritty font-ibm-plex font-input visual-studio-code

brew doctor
