#!/usr/bin/env bash

source utility/command.sh

if is_command_not_in_path brew; then
	printf 'Installing brew...'
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update

xargs brew install <package-manager/packages/common.txt
xargs brew install <package-manager/packages/brew.txt
xargs brew cask install <package-manager/packages/brew-cask.txt

brew doctor
