#!/usr/bin/env bash

source utility/command.sh

xargs sudo pacman -S --needed <package-manager/packages/common.txt
xargs sudo pacman -S --needed <package-manager/packages/pacman.txt

if is_command_not_in_path yay; then
	git clone --depth 1 https://aur.archlinux.org/yay.git
	(
		cd yay/ || exit
		makepkg -si
	)
	rm -rf yay/
fi

yay -S --needed gotop lazygit starship ttf-input

xargs yay -S --needed <package-manager/packages/aur.txt
