#!/usr/bin/env bash

source utility/command.sh

sudo pacman -S --needed alacritty bat code exa fish git git-lfs jq nodejs npm shellcheck shfmt python python-pip ttf-ibm-plex tmux wget xclip

if is_command_not_in_path yay; then
	git clone --depth 1 https://aur.archlinux.org/yay.git
	(
		cd yay/ || exit
		makepkg -si
	)
	rm -rf yay/
fi

yay -S --needed gotop lazygit starship ttf-input
