#!/usr/bin/env bash

SESSION='BrunoRoque06'

tmux new-session -s $SESSION -n 'dotfiles' -d
tmux send-keys "cd $HOME/dotfiles" C-m

tmux new-window -t $SESSION:1 -n 'Website'
tmux split-window -v -t $SESSION:1.0
tmux send-keys -t $SESSION:1.0 "cd $HOME/Documents/brunoroque06.github.io" C-m
tmux send-keys -t $SESSION:1.1 "cd $HOME/Documents/brunoroque06.github.io; make serve" C-m

tmux new-window -t $SESSION:2 -n 'Genetic Algorithm'
tmux send-keys "cd $HOME/go/src/github.com/brunoroque06/geneticalgorithm" C-m

tmux attach-session -t $SESSION

