#!/usr/bin/env bash

SESSION='Spoud'

tmux new-session -s $SESSION -n 'dotfiles' -d
tmux send-keys "cd $HOME/dotfiles" C-m

tmux new-window -t $SESSION:1 -n 'Monorepository'
tmux send-keys 'mrcd; gl' C-m

tmux new-window -t $SESSION:2 -n 'Catalog'
tmux split-window -v -t $SESSION:2.0

tmux send-keys -t $SESSION:2.0 'mrcd; docker run -p 27017:27017 mongo' C-m
tmux send-keys -t $SESSION:2.1 'mrcd; bazel run //catalog/service:app' C-m

tmux attach-session -t $SESSION

