#!/usr/bin/env bash

printf 'Setting up Zsh...\n'

ln -fsv "$PWD"/zsh/.aliases "$HOME"/.aliases
ln -fsv "$PWD"/zsh/.zsh_plugins "$HOME"/.zsh_plugins
ln -fsv "$PWD"/zsh/.zshrc "$HOME"/.zshrc

source zsh/.zsh_plugins
zsh_plugins_install
