#!/usr/bin/env pwsh -NoProfile

# @raycast.schemaVersion 1
# @raycast.title Convert Snippets
# @raycast.mode compact
# @raycast.icon ⌨️

$snippets = Get-Content $HOME/Projects/dots/raycast/snippets.json | ConvertFrom-Json

$file = New-Object System.Text.StringBuilder
$file.Append('<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><array>')

foreach ($s in $snippets) {
    $text = $s.text -replace '\{[a-z]+\}', ''
    $file.Append('<dict><key>phrase</key><string>').Append($text).Append('</string><key>shortcut</key><string>').Append($s.keyword).Append('</string></dict>')
}

$file.Append('</array></plist>')

$file.ToString() | Out-File $HOME/Projects/dots/raycast/snippets.plist
