#!/usr/bin/env pwsh -NoProfile

# @raycast.schemaVersion 1
# @raycast.title Type Password
# @raycast.mode compact
# @raycast.icon 🔑
# @raycast.argument1 { "placeholder": "code", "type": "dropdown", "data": [{ "title": "false", "value": "false" }, { "title": "true", "value": "true" }], "optional": true }

. ./os.ps1

$pw = Invoke-Expression 'security find-generic-password -a brunroqu -s axpo -w'
TypeKeys -Esc $true -Enter $true $pw

if ($args[0] -eq 'true') {
    Start-Sleep -Seconds 15
    $msg = Invoke-Expression 'sqlite3 ~/Library/Messages/chat.db ''select text from message where text like "passcode: %your ip-address: %country: %" order by date desc limit 1'''
    $match = [System.Text.RegularExpressions.Regex]::Match($msg, 'PASSCODE: (.*?) ')
    if (-not $match.Success) {
        throw 'Could not read code'
    }
    TypeKeys $match.Groups[1].Value
}
