#!/usr/bin/env osascript

# @raycast.schemaVersion 1
# @raycast.title Type Password
# @raycast.mode compact
# @raycast.icon 🔑

delay 2

tell application "System Events"
  keystroke "something"
end tell
