#!/usr/bin/env bash

printf 'Setting up fish...\n'

mkdir -p "$HOME/.config/fish/functions"

ln -fns "$PWD/fish/functions/fish_prompt.fish" "$HOME/.config/fish/functions/fish_prompt.fish"
ln -fns "$PWD/fish/config.fish" "$HOME/.config/fish/config.fish"
ln -fns "$PWD/fish/fishfile" "$HOME/.config/fish/fishfile"

curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
fish -c fisher
