#!/usr/bin/env bash

printf 'Setting up fish...\n'

mkdir -p "$HOME"/.config/fish/functions

ln -fsv "$PWD"/fish/functions/fish_prompt.fish "$HOME"/.config/fish/functions/fish_prompt.fish
touch "$HOME"/.config/fish/functions/fish_mode_prompt.fish
ln -fsv "$PWD"/fish/functions/weather.fish "$HOME"/.config/fish/functions/weather.fish
ln -fsv "$PWD"/fish/config.fish "$HOME"/.config/fish/config.fish
ln -fsv "$PWD"/fish/fishfile "$HOME"/.config/fish/fishfile

curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
fish -c fisher

ln -fsv "$PWD"/fish/functions/abbrs_setup.fish "$HOME"/.config/fish/functions/abbrs_setup.fish
ln -fsv "$PWD"/fish/abbrs.fish "$HOME"/.config/fish/abbrs.fish
fish -c abbrs_setup
